### ISSUE TITLE
Any way to get this to work in plain AS3?

### ISSUE THREAD

**Issue by EddieOne** [charlesbihis/actionscript-oauth2#6]
I realize adobe has made stageWebView only available in AIR and not the web player. This seems like an important part. I found a possible alternative https://github.com/talltyler/HTMLWrapper but it doesn't look very promising. Is there a way to get this working on desktops without writing a browser in AS3?

Thanks

**Comment by charlesbihis** [comment]
Hi EddieOne.  Sorry, but no, this library requires the StageWebView to handle the user agent.  Without writing your own alternative, this library has a hard dependency on the AIR SDK.

**Comment by dizag** [comment]
hey,
I'm spend week with oauth2 for air (main goal it's mobile app ... without web & domain), i read ton of comments and doc ... i succeed with google but facebook is a pain. I'm still stick, can you give me a hint how can happens to work...
last thing loaded in stageWebView is https://www.facebook.com/connect/login_success.html?code=AQAWmvxLoMY....
but i can't handle it, please help :)

**Comment by dizag** [comment]
hi charlesbihis,
i succeed to receive https://www.facebook.com/connect/login_success.html#access_token=CAAC5ZBZCZCQG....
trough ImplicitGrant ... 
but now 
oauth2.addEventListener(GetAccessTokenEvent.TYPE, onGetAccessToken); 
seems didn't fire,
any suggestions ?

**Comment by charlesbihis** [comment]
You should see a log statement outputting your access token.  If you see this, then the event is being fired.  If not, perhaps there was an error in parsing your access token from the redirect URI.  See com.adobe.protocols.oauth2.OAuth2.as, line 420.

Hope that helps.

**Comment by dizag** [comment]
Thank you, for FB is exactly there, in condition
locationChangeEvent.location.indexOf(implicitGrant.redirectUri) == 0  ...

**Comment by ghost** [comment]
Hi. Been working with the oAuth framework and have found since updating to the latest version of Flash and AIR that my oAuth displayed page doesn't render correctly on Windows. 

https://www.dropbox.com/s/r71i0clc7axhfuk/oauthWindows.jpg?dl=0

On Mac it's fine.

https://www.dropbox.com/s/s9ihfiqxpvlvfz7/oauthMac.jpg?dl=0

Any suggestions that I might follow up on?

**Comment by charlesbihis** [comment]
Hi John,

It looks like the StageWebView component in AIR on Windows doesn't like something in the user-consent page.  I would try taking the authorization URL for that page and popping it directly into a StageWebView on both platforms and seeing how they render.  I would check for things like image locations and CSS.  Perhaps an issue with SSL, an expired cert, or certain CSS directives that StageWebView doesn't support.  If that doesn't work, I would try loading each individual component in a separate StageWebView.  For instance, I would try _just_ loading the sport ngin logo alone on Windows and see if that works.  Hope that helps.
